### ISSUE TITLE
wrangler dev consistently crashes with "access violation" (0xc0000005) on Windows 11

### ISSUE THREAD

**Issue by Sn0wo2** [cloudflare/workerd#4668]
### What versions & operating system are you using?

⛅️ wrangler 4.23.0, node v22.15.0, npm v11.4.2, bun v1.2.18

### Describe the Bug

**Summary of the Problem:**
The `workerd` runtime used by `wrangler dev` seems to have a critical incompatibility with my Windows environment, leading to a `0xc0000005` exception.

**Troubleshooting Steps I've Exhaustively Performed:**

1.  **Verified System Dependencies:** Confirmed the latest Microsoft Visual C++ Redistributables (x64 & x86) are installed.
2.  **Isolated the Project:** The crash occurs even with a brand new, minimal project created by `npx wrangler init`. This rules out my specific project's code or configuration.
3.  **Isolated the JS Runtime:** The crash happens identically when using either Node.js v22 or Bun.
4.  **Isolated the Wrangler Version:** Rolling back to previous versions of `wrangler` did not fix the issue.
5.  **Cleared All State:** I have completely removed all `.wrangler` directories (both global and local) and reinstalled all `node_modules`.
6.  **Checked Environmental Factors:**
    *   The issue persists even after disabling my system-wide proxy.
    *   The issue persists after temporarily disabling all antivirus/security software.

**Environment:**

版本	Windows 11 家庭中文版
版本号	24H2
安装日期	‎2025/‎6/‎26
操作系统版本	26100.4484
体验	Windows 功能体验包 1000.26100.128.0

⛅️ wrangler 4.23.0, node v22.15.0, npm v11.4.2, bun v1.2.18

<img width="947" height="315" alt="Image" src="https://github.com/user-attachments/assets/38b1415d-c0da-4e97-a029-95ba2fb4fdd6" />

1.  Run `npx wrangler init hello-worker`.
2.  `cd hello-worker`.
3.  Run `npx wrangler dev --log-level debug`.

### Please provide any relevant error logs

```
--- 2025-07-04T13:45:13.989Z debug
🪵  Writing logs to "C:\Users\xuexu\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2025-07-04_13-45-13_808.log"
---

--- 2025-07-04T13:45:13.989Z log
Proxy environment variables detected. We'll use your proxy for fetch requests.
---

--- 2025-07-04T13:45:14.038Z log
[90m[39m
[90mCloudflare collects anonymous telemetry about your usage of Wrangler. Learn more at https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/telemetry.md[39m
---

--- 2025-07-04T13:45:14.043Z debug
Metrics dispatcher: Posting data {"deviceId":"fc6ecee9-e5f8-4cf1-9fc8-f062638f049e","event":"wrangler command started","timestamp":1751636714043,"properties":{"amplitude_session_id":1751636714037,"amplitude_event_id":0,"wranglerVersion":"4.23.0","osPlatform":"Windows","osVersion":"Windows 11 Home China","nodeVersion":22,"packageManager":"npm","isFirstUsage":false,"configFileType":"jsonc","isCI":false,"isPagesCI":false,"isWorkersCI":false,"isInteractive":true,"hasAssets":false,"argsUsed":[],"argsCombination":"","command":"wrangler dev","args":{"xJsonConfig":true,"j":true,"latest":true,"noBundle":false,"remote":false,"r":false,"testScheduled":false,"xVectorizeBindToProd":false,"xImagesLocalMode":false}}}
---

--- 2025-07-04T13:45:14.059Z debug
.env file not found at ".env". Continuing... For more details, refer to https://developers.cloudflare.com/workers/wrangler/system-environment-variables/
---

--- 2025-07-04T13:45:14.086Z log

 ⛅️ wrangler 4.23.0
[38;2;255;136;0m───────────────────[39m
---

--- 2025-07-04T13:45:14.311Z debug
.env file not found at ".dev.vars". Continuing... For more details, refer to https://developers.cloudflare.com/workers/wrangler/system-environment-variables/
---

--- 2025-07-04T13:45:14.405Z debug
RemoteRuntimeController teardown beginning...
---

--- 2025-07-04T13:45:14.405Z debug
RemoteRuntimeController teardown complete
---

--- 2025-07-04T13:45:14.407Z log
[2m⎔ Starting local server...[22m
---

--- 2025-07-04T13:45:15.404Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mThere was an access violation in the runtime.[0m

  On Windows, this may be caused by an outdated Microsoft Visual C++ Redistributable library.
  Check that you have the latest version installed.
  See [4mhttps://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist[0m.


---

--- 2025-07-04T13:45:15.404Z debug
*** Received structured exception #0xc0000005: access violation; stack: 7fff04f6929f 7ff71bb12cca 7ff71bb12d93 7ff71bab13ac 7ff71bab1357 7ff71af77f1f 7ff71af78390 7ff71998385f 7ff71b103a4f 7ff71b10a976 7ff71b103f53 7ff71b10a976 7ff71b1018ec 7ff719971fc7 7ff71c2b1a7f 7fff2208e8d6 7fff2313c34b
---

--- 2025-07-04T13:45:15.407Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mThere was an access violation in the runtime.[0m

  On Windows, this may be caused by an outdated Microsoft Visual C++ Redistributable library.
  Check that you have the latest version installed.
  See [4mhttps://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist[0m.


---

--- 2025-07-04T13:45:15.407Z debug
*** Received structured exception #0xc00000

05: access violation; stack: 7fff04f6929f 7ff71bb12cca 7ff71bb12d93 7ff71bab13ac 7ff71bab1357 7ff71af77f1f 7ff71af78390 7ff71998385f 7ff71b103a4f 7ff71b10a976 7ff71b103f53 7ff71b10a976 7ff71b1018ec 7ff719971fc7 7ff71c2b1a7f 7fff2208e8d6 7fff2313c34b
---

--- 2025-07-04T13:45:15.478Z debug
Error in ProxyController: Could not connect to InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20871:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-07-04T13:45:15.479Z debug
=> Error contextual data: {
  config: {
    name: 'hello-worker',
    config: 'D:\\webProject\\hello-worker\\wrangler.jsonc',
    compatibilityDate: '2025-07-04',
    compatibilityFlags: [],
    complianceRegion: undefined,
    entrypoint: 'D:\\webProject\\hello-worker\\src\\index.js',
    projectRoot: 'D:\\webProject\\hello-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: 'D:\\webProject\\hello-worker\\src',
      moduleRules: [],
      minify: undefined,
      keepNames: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    containers: undefined,
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: 'D:\\webProject\\hello-worker\\.wrangler\\state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false,
      experimentalRemoteBindings: false,
      enableContainers: true,
      dockerPath: 'docker',
      containerEngine: '//./pipe/docker_engine',
      containerBuildId: '13b58346'
    },
    legacy: { site: undefined, enableServiceEnvironments: false },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined,
    tailConsumers: []
  },
  bundle: undefined
}
---

--- 2025-07-04T13:45:15.488Z debug
Error in ProxyController: Failed to start ProxyWorker or InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20871:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-07-04T13:45:15.488Z debug
=> Error contextual data: {
  config: {
    name: 'hello-worker',
    config: 'D:\\webProject\\hello-worker\\wrangler.jsonc',
    compatibilityDate: '2025-07-04',
    compatibilityFlags: [],
    complianceRegion: undefined,
    entrypoint: 'D:\\webProject\\hello-worker\\src\\index.js',
    projectRoot: 'D:\\webProject\\hello-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: 'D:\\webProject\\hello-worker\\src',
      moduleRules: [],
      minify: undefined,
      keepNames: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    containers: undefined,
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: 'D:\\webProject\\hello-worker\\.wrangler\\state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false,
      experimentalRemoteBindings: false,
      enableContainers: true,
      dockerPath: 'docker',
      containerEngine: '//./pipe/docker_engine',
      containerBuildId: '13b58346'
    },
    legacy: { site: undefined, enableServiceEnvironments: false },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined,
    tailConsumers: []
  },
  bundle: undefined
}
---

--- 2025-07-04T13:45:15.488Z debug
Error in ProxyController: Failed to send message to InspectorProxyWorker: {"type":"reloadStart"}
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20871:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-07-04T13:45:15.488Z debug
=> Error contextual data: {
  config: {
    name: 'hello-worker',
    config: 'D:\\webProject\\hello-worker\\wrangler.jsonc',
    compatibilityDate: '2025-07-04',
    compatibilityFlags: [],
    complianceRegion: undefined,
    entrypoint: 'D:\\webProject\\hello-worker\\src\\index.js',
    projectRoot: 'D:\\webProject\\hello-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: 'D:\\webProject\\hello-worker\\src',
      moduleRules: [],
      minify: undefined,
      keepNames: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    containers: undefined,
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: 'D:\\webProject\\hello-worker\\.wrangler\\state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false,
      experimentalRemoteBindings: false,
      enableContainers: true,
      dockerPath: 'docker',
      containerEngine: '//./pipe/docker_engine',
      containerBuildId: '13b58346'
    },
    legacy: { site: undefined, enableServiceEnvironments: false },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined,
    tailConsumers: []
  },
  bundle: undefined
}
---

--- 2025-07-04T13:45:15.489Z log

---

--- 2025-07-04T13:45:15.491Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mThe Workers runtime failed to start. There is likely additional logging output above.[0m


---

--- 2025-07-04T13:45:15.491Z debug
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20871:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48)
---

--- 2025-07-04T13:45:15.491Z log
[32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose[0m
---

--- 2025-07-04T13:45:15.572Z debug
Error in LocalRuntimeController: Error reloading local server
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20871:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48)
    at async #waitForReady (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:20946:5)
    at async #onBundleComplete (D:\webProject\hello-worker\node_modules\wrangler\wrangler-dist\cli.js:174526:33)
    at async Mutex.runWith (D:\webProject\hello-worker\node_modules\miniflare\dist\src\index.js:2197:48) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-07-04T13:45:15.572Z debug
=> Error contextual data: undefined
---

--- 2025-07-04T13:45:17.300Z debug
Sentry: Capturing exception MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
---

--- 2025-07-04T13:45:17.308Z debug
Metrics dispatcher: Posting data {"deviceId":"fc6ecee9-e5f8-4cf1-9fc8-f062638f049e","event":"wrangler command errored","timestamp":1751636717308,"properties":{"amplitude_session_id":1751636714037,"amplitude_event_id":1,"wranglerVersion":"4.23.0","osPlatform":"Windows","osVersion":"Windows 11 Home China","nodeVersion":22,"packageManager":"npm","isFirstUsage":false,"configFileType":"jsonc","isCI":false,"isPagesCI":false,"isWorkersCI":false,"isInteractive":true,"hasAssets":false,"argsUsed":[],"argsCombination":"","command":"wrangler dev","args":{"xJsonConfig":true,"j":true,"latest":true,"noBundle":false,"remote":false,"r":false,"testScheduled":false,"xVectorizeBindToProd":false,"xImagesLocalMode":false},"durationMs":3299,"durationSeconds":3.299,"durationMinutes":0.054983333333333335}}
---
```

**Comment by edmundhung** [comment]
Hi @Sn0wo2 👋,

Thanks for reporting this! Could you let us know which exact version of the Microsoft Visual C++ Redistributable you have installed on your machine? We have seen this crop up before, and it's usually resolved by upgrading to the very latest VC++ Redistributable (for example, see issue cloudflare/workers-sdk#6170).

You can check and download the newest supported version here:

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by Sn0wo2** [comment]
> Hi [@Sn0wo2](https://github.com/Sn0wo2) 👋,
> 
> Thanks for reporting this! Could you let us know which exact version of the Microsoft Visual C++ Redistributable you have installed on your machine? We have seen this crop up before, and it's usually resolved by upgrading to the very latest VC++ Redistributable (for example, see issue [#6170](https://github.com/cloudflare/workers-sdk/issues/6170)).
> 
> You can check and download the newest supported version here:
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

Hello, I've tried installing the latest version of `Microsoft Visual C++ Redistributable` before opening issue, here is a screenshot of my `Microsoft Visual C++ Redistributable` version

<img width="923" height="274" alt="Image" src="https://github.com/user-attachments/assets/1e1fa146-1136-4cd2-8c2d-b88c3cb20787" />

**Comment by Mion354D** [comment]
Same problem here. Wrangler keeps crashing/getting stuck.
Using latest C++ redistributable (till Jul 09).

And I found that when I turn on TUN mode proxy, Wrangler works well.
I live in China, where **workers.dev** is almost completely blocked. Issue author uses Windows in Chinese, so maybe he/she also lives in China.

Is there some necessary step in the Wrangler startup process to access the Cloudflare Worker domain without going through the system proxy? Guessing when it gets stuck, it crashes Wrangler.

**Comment by Sn0wo2** [comment]
> Same problem here. Wrangler keeps crashing/getting stuck. Using latest C++ redistributable (till Jul 09).
> 
> And I found that when I turn on TUN mode proxy, Wrangler works well. I live in China, where **workers.dev** is almost completely blocked. Issue author uses Windows in Chinese, so maybe he/she also lives in China.
> 
> Is there some necessary step in the Wrangler startup process to access the Cloudflare Worker domain without going through the system proxy? Guessing when it gets stuck, it crashes Wrangler.

ty, but i tried setting the **system proxy** and making sure the proxy can access `workers.dev`, but it still doesnt work 
I also tried it without setting the **system proxy** env and it still crash...
```
--- 2025-07-04T13:45:13.989Z log
Proxy environment variables detected. We'll use your proxy for fetch requests.
---
```

**Comment by jamesopstad** [comment]
I've moved this to the `workerd` repo as it looks like a `workerd` issue. Could you try running a basic `workerd` only example on your machine to see if that works? https://github.com/cloudflare/workerd/tree/main/samples/helloworld

**Comment by Sn0wo2** [comment]
```log
C:\Users\xuexu\Downloads>workerd.exe serve config.capnp
*** Received structured exception #0xc0000005: access violation; stack: 7ff83a9e929f 7ff6a4e46f5d 7ff6a4e47023 7ff6a4dd981c 7ff6a4dd97d0 7ff6a44d105a 7ff6a44d14d0 7ff6a31e3bcf 7ff6a4660aec 7ff6a4667c26 7ff6a466101d 7ff6a4667c26 7ff6a465e822 7ff6a31d2012 7ff6a5c266df 7ff857a7e8d6 7ff85817c34b
```

it doesnt seem to be working...

**Comment by docrst** [comment]
I just got this error on win 11, is there a fix or workaround??  EVERY REFERENCE LINK TO THIS ENDS IN A CLOSED DUPE, AND ALL THE LINKS ALSO CLOSED AS DUPE, AND IT GOES ON FOREVER!!!

**Comment by Sn0wo2** [comment]
> I just got this error on win 11, is there a fix or workaround?? EVERY REFERENCE LINK TO THIS ENDS IN A CLOSED DUPE, AND ALL THE LINKS ALSO CLOSED AS DUPE, AND IT GOES ON FOREVER!!!

I solved it after reinstall win11

**Comment by docrst** [comment]
> > I just got this error on win 11, is there a fix or workaround?? EVERY REFERENCE LINK TO THIS ENDS IN A CLOSED DUPE, AND ALL THE LINKS ALSO CLOSED AS DUPE, AND IT GOES ON FOREVER!!!
> 
> I solved it after reinstall win11

That is drastic to resolve an error in a 3rd-party app; it should be a Cloudflare resolution, not an OS issue!!
